#- hosts: master-1
#  become: yes
#  become_user: root
#  tasks:
#
#  - include_role:
#      name: kubernetes-upgrade
#      tasks_from: first-master

- hosts: master-3
  serial: 1
  become: yes
  become_user: root
  tasks:

  - include_role:
      name: kubernetes-upgrade
      tasks_from: other-masters
