---
- name: Drain the worker node
  shell: kubectl drain {{ansible_hostname}} --ignore-daemonsets
  register: drain_node
  delegate_to: "{{groups['masters'][0]}}"

- name: install kubeadm
  apt:
    name: "kubeadm={{ kubeadm_version }}"
    state: present
    update_cache: true

- name: "Kubeadm upgrade node"
  shell: kubeadm upgrade node
  register: rslt

- name:
  debug:
    var: rslt

- pause:
    prompt: "Proceed with kubelet upgrade and restart"

- name: install kubelet
  apt:
    name: "kubelet={{ kubeadm_version }}"
    state: present
    update_cache: true

- name: Restart kubelet
  systemd:
    state: restarted
    daemon_reload: yes
    name: kubelet
    enabled: yes

- name: install kubectl
  apt:
    name: "kubectl={{ kubeadm_version }}"
    state: present
    update_cache: true

- name: Uncordon the worker node
  shell: kubectl uncordon {{ansible_hostname}} --ignore-daemonsets
  delegate_to: "{{groups['masters'][0]}}"
