---
- name: Restart Haproxy
  systemd:
    name: haproxy
    state: restarted
    enabled: true

- name: Reload Haproxy
  systemd:
    name: haproxy
    state: reloaded

- name: Restart Keepalived
  systemd:
    name: keepalived
    state: restarted
    enabled: true

